### PR TITLE
Added Ubuntu theme modifications.

### PR DESCRIPTION
**Pull request by nathan-osman**
Here is the first of a few theme customizations I have implemented. I am not a Ruby expert, so hopefully I didn't do anything silly.

### CODE REVIEW

**Comment by marcoceppi** [comment]
This looks great, just a few things for you to update. Can you make your changes and squash back down to one commit then resubmit? Really eager to get this in today and I don't want to squash/remove your commit by changing this manually

**Comment by nathan-osman** [comment]
I'd love to... but I'm not terribly familiar with how this works in Git. From my limited knowledge, I am guessing I need to:
- reset HEAD to the previous commit
- make the changes again, this time being sure to follow your suggestions
- make another commit and push

Can you please confirm that this is the correct way to go about this?

**Comment by marcoceppi** [comment]
@nathan-osman You'll basically just make the changes, run a commit something like "Implement Feedback" (doesn't matter since it's going to be rebased). Then run `git rebase -i HEAD~2` this will run an interactive rebase. You'll see your two commits, the first one you made and the changes. Change the second line from pick to squash, save and close the file. Then you'll have a second file to edit. This will be the commit message. You can just delete the second commit message and write the file out. Then the commits will be merged. From there just `git push -f` your changes and comment here :smiley:

**Comment by nathan-osman** [comment]
Okay. I will do that. Thanks for clarifying.

**Comment by nathan-osman** [comment]
Okay, I think we're good to go!

**Comment by marcoceppi** [comment]
Since I break everything I touch, I'm going to merge this manually

**Pull request closed without merging**
